name: Taxonomy Re API tests on:
  [push, pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: run tests
      shell: bash
      env:
        GITHUB_ACTIONS_CI: 1
      run: |
        make test

